<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FaceVerification.Application\FaceVerification.Application.csproj" />
    <ProjectReference Include="..\FaceVerification.Infrastructure\FaceVerification.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>
</Project>
