// <auto-generated />
using System;
using FaceVerification.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaceVerification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FaceVerificationDbContext))]
    partial class FaceVerificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaceVerification.Domain.FaceVerificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AppliedMatchThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("AppliedNonMatchThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("CapturedQualityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<int>("DetectedCapturedFaces")
                        .HasColumnType("integer");

                    b.Property<int>("DetectedReferenceFaces")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<double>("ReferenceQualityScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("SimilarityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VerificationSessionId")
                        .IsUnique();

                    b.ToTable("face_verification_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_face_verification_results_similarity", "\"SimilarityScore\" IS NULL OR (\"SimilarityScore\" >= -1 AND \"SimilarityScore\" <= 1)");

                            t.HasCheckConstraint("ck_face_verification_results_thresholds", "\"AppliedNonMatchThreshold\" < \"AppliedMatchThreshold\"");
                        });
                });

            modelBuilder.Entity("FaceVerification.Domain.VerificationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LivenessEvidenceHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("LivenessTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NonceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_verification_sessions_expires_at");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_verification_sessions_status_started");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_verification_sessions_user_created");

                    b.ToTable("verification_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_verification_sessions_expiry", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("ck_verification_sessions_status", "\"Status\" BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("FaceVerification.Domain.FaceVerificationRecord", b =>
                {
                    b.HasOne("FaceVerification.Domain.VerificationSession", null)
                        .WithOne("Result")
                        .HasForeignKey("FaceVerification.Domain.FaceVerificationRecord", "VerificationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaceVerification.Domain.VerificationSession", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
